seed: 42
epochs: 100
batch_size: 32
val_split: 0.2
count: 2000
preprocessor:
  rescaling:
    scale: 0.007843137254902
    offset: -1
  patches:
    patch_size: [64, 64]
augmenter:
  flip:
    mode: horizontal_and_vertical
model:
  name: bigan
  generator:
    optimizer_name: adam
    optimizer_args:
      learning_rate: 0.0001
      beta_1: 0.2
    input_shape: [128]
    block_filters: [256, 128, 64]
    output_shape: [64, 64, 1]
    base_kernel_size: 8
  encoder:
    optimizer_name: adam
    optimizer_args:
      learning_rate: 0.0001
      beta_1: 0.2
    input_shape: [64, 64, 1]
    block_filters: [64, 128, 256]
    output_shape: [128]
    base_kernel_size: 8
  discriminator:
    optimizer_name: adam
    optimizer_args:
      learning_rate: 0.0001
      beta_1: 0.2
    input_shape: [[64, 64, 1], [128]]
    block_filters: [64, 128, 256]
    output_shape: [1]
    base_kernel_size: 8
detector:
  name: bigan
  preprocessor:
    rescaling:
      scale: 0.007843137254902
      offset: -1
    resizepadcrop:
      target_height: 704
      target_width: 1024
  postprocessor:
    resizepadcrop:
      target_height: 700
      target_width: 1024
  generator:
    input_shape: [null, null, 128]
    block_filters: [256, 128, 64]
    output_shape: [null, null, 1]
    base_kernel_size: 8
  encoder:
    input_shape: [null, null, 1]
    block_filters: [64, 128, 256]
    output_shape: [null, null, 128]
    base_kernel_size: 8
  discriminator:
    input_shape: [[null, null, 1], [null, null, 128]]
    block_filters: [64, 128, 256]
    output_shape: [null, null, 1]
    base_kernel_size: 8

